apiVersion: v1
kind: Service
metadata:
  name: avangrid-frontend-service
  labels:
    app: nginx-frontend
spec:
  type: ClusterIP
  selector:
    app: nginx-frontend
  ports:
    - port: 80
      targetPort: 80
``