apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-azurefile-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # empty for static binding
  azureFile:
    secretName: azure-files-secret
    shareName: <AZURE_FILE_SHARE_NAME>   # ðŸ‘ˆ your existing file share name
    readOnly: false