apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""   # must match PV (empty) for static binding
  resources:
    requests:
      storage: 5Gi
  volumeName: frontend-azurefile-pv