apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avangrid-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Optional: turn off buffering for APIs, tune timeouts, etc.
    # nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    # UI
    - host: ui.company.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avangrid-frontend-service
                port:
                  number: 80
    # API
    - host: api.company.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avangrid-backend-service
                port:
                  number: 80
  # Optional TLS
  # tls:
  #   - hosts:
  #       - ui.company.com
  #       - api.company.com
  #     secretName: wildcard-cert